### PR TITLE
Update README.md with label definitions

### PR DESCRIPTION
**Pull request by emilyriederer**
Please let me know if you are aligned with using the labels I describe below and including these descriptions in the README. I'd love to make these ideas (of which there will hopefully be many more!) as navigable as possible. 

(Would also request review from Sydney but GH won't let me)

### CODE REVIEW

**Comment by willdebras** [comment]
Hi I think these look great and cover the bases of what we might want to label. We can always add more if we want later. Happy to merge if @angela-li thinks these are good.

**Review by willdebras — APPROVED** [review]
Looks good!

**Review by angela-li — APPROVED** [review]
Yes, I think this makes sense! This is a nice way to split up the labeling. Thanks for this, Emily!

**Comment by angela-li** [comment]
Btw @willdebras it'd be nice to create a "chircollab" label to stick onto all of the issues (potentially after the event? but also during it), so that they can be categorized under our event - see example of this type of thing in action here: https://github.com/search?q=is%3Aissue+is%3Aopen+label%3A%22tidy-dev-day+%3Anerd_face%3A%22

**Pull request merged**
